-- Charter Analytics
-- Query 1: Most Attended Events
-- Returns events ranked by number of verified attendees

SELECT 
    E.TITLE AS EVENT_NAME,
    COUNT(A.ATTENDANCE_ID) AS TOTAL_ATTENDEES
FROM EVENT E
JOIN REGISTRATION R ON E.EVENT_ID = R.EVENT_ID
JOIN ATTENDANCE A ON R.REG_ID = A.REG_ID
WHERE A.ATTENDED = 'YES'
GROUP BY E.TITLE
ORDER BY COUNT(A.ATTENDANCE_ID) DESC;