-- Charter Analytics
-- Query 2: Top Rated Events
-- Returns events ranked by average feedback rating

SELECT 
    E.TITLE AS EVENT_NAME,
    ROUND(AVG(F.RATING), 2) AS AVERAGE_RATING,
    COUNT(F.FEEDBACK_ID) AS TOTAL_REVIEWS
FROM EVENT E
JOIN REGISTRATION R ON E.EVENT_ID = R.EVENT_ID
JOIN ATTENDANCE A ON R.REG_ID = A.REG_ID
JOIN FEEDBACK F ON A.ATTENDANCE_ID = F.ATTENDANCE_ID
GROUP BY E.TITLE
ORDER BY AVG(F.RATING) DESC;