-- Charter Analytics
-- Query 3: Club Budget Utilization
-- Returns budget utilization percentage per club

SELECT 
    C.CLUB_NAME,
    SUM(B.TOTALAMOUNT) AS TOTAL_BUDGET,
    SUM(B.AMOUNTSPENT) AS TOTAL_SPENT,
    SUM(B.TOTALAMOUNT) - SUM(B.AMOUNTSPENT) AS REMAINING,
    ROUND((SUM(B.AMOUNTSPENT) / SUM(B.TOTALAMOUNT)) * 100, 2) AS UTILIZATION_PERCENT
FROM CLUB C
JOIN BUDGET B ON C.CLUB_ID = B.CLUB_ID
GROUP BY C.CLUB_NAME
ORDER BY UTILIZATION_PERCENT DESC;