-- Charter Analytics
-- Query 4: Most Active Members
-- Returns members ranked by number of event registrations

SELECT 
    M.NAME AS MEMBER_NAME,
    M.DEGREE,
    M.SEMESTER,
    COUNT(R.REG_ID) AS TOTAL_REGISTRATIONS,
    SUM(CASE WHEN A.ATTENDED = 'YES' THEN 1 ELSE 0 END) AS EVENTS_ATTENDED
FROM MEMBER M
JOIN REGISTRATION R ON M.MEMBER_ID = R.MEMBER_ID
LEFT JOIN ATTENDANCE A ON R.REG_ID = A.REG_ID
GROUP BY M.NAME, M.DEGREE, M.SEMESTER
ORDER BY COUNT(R.REG_ID) DESC;