-- Charter Analytics
-- Query 5: Sponsor Contribution Ranking
-- Returns sponsors ranked by total sponsorship amount

SELECT 
    S.SPONSORNAME AS SPONSOR,
    S.CONTACTPERSON,
    S.SPONSORAMOUNT AS AMOUNT_CONTRIBUTED,
    COUNT(E.EVENT_ID) AS EVENTS_SPONSORED
FROM SPONSOR S
JOIN EVENT E ON S.SPONSOR_ID = E.SPONSOR_ID
GROUP BY S.SPONSORNAME, S.CONTACTPERSON, S.SPONSORAMOUNT
ORDER BY S.SPONSORAMOUNT DESC;