-- Charter Analytics
-- Query 8: Member Retention Per Semester
-- Returns membership growth trend over time

SELECT 
    TO_CHAR(JOINDATE, 'Mon YYYY') AS PERIOD,
    COUNT(MEMBERSHIP_ID) AS NEW_MEMBERSHIPS,
    COUNT(DISTINCT MEMBER_ID) AS UNIQUE_MEMBERS,
    COUNT(DISTINCT CLUB_ID) AS CLUBS_JOINED
FROM MEMBERSHIP
GROUP BY TO_CHAR(JOINDATE, 'Mon YYYY'),
         TO_CHAR(JOINDATE, 'YYYY-MM')
ORDER BY TO_CHAR(JOINDATE, 'YYYY-MM');